name: Render

on:
  push:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1

      - name: Render quarto document
        run: quarto render diamonds.qmd

      - name: Publish to GitHub Pages
        if: github.event_name != 'pull request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: docs
