jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
  steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    - uses: r-lib/actions/setup-r-dependencies@v2
    - uses: quarto-dev/quarto-actions/install-quarto@v1
    - uses: stefanzweifel/git-auto-commit-actions@v5

    - name: Render quarto document
      run: quarto render diamonds.qmd

    - name: Publish to GitHub Pages
      if: github.event_name != 'pull request'
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        branch: gh-pages
        folder: docs
