name: Render

on:
  push:
    # Maybe we don't want to render if not pushing on main
    # Commented out so that always render, just don't publish if on other branch
    # branches: main

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1

      - name: Render quarto document
        run: quarto render index.qmd --output-dir html

      - name: Publish to GitHub Pages
        # only publish if pushed to main (production environment)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: html
